#+TITLE: 16th IMA International Conference on Cryptography and Coding
#+BLOG: martinralbrecht
#+POSTID: 1410
#+DATE: [2017-06-10 Sat 13:09]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: cryptography
#+TAGS:cryptography, coding theory, conference

#+DESCRIPTION:

[[https://www.qub.ac.uk/sites/CSIT/IMACC2017/][IMA-CCC]] is a crypto and coding theory conference biennially held in the UK. It was previously held in Cirencester. So you might have heard of it as the “Cirncester” conference. However, it has been moved to Oxford, so calling it Cirencester now is a bit confusing. Anyway, it is happening again this year. IMA is a small but fine conference with the added perk of being right before Christmas. This is great because around that time of the year Oxford is a fairly Christmas-y place to be.

#+BEGIN_CENTER
*12 – 14 December 2017, St Catherine’s College, University of Oxford*
#+END_CENTER

#+HTML:<!--more-->

** Call for Papers

The mathematical theory and practice of cryptography and coding underpins the provision of effective security and reliability for data communication, processing and storage. Theoretical and practical advances in the fields of cryptography and coding are therefore a key factor in facilitating the growth of data communications and data networks of various types. Thus, this sixteenth International Conference in an established and successful IMA series on the theme of “Cryptography and Coding” is both timely and relevant. Original research papers on all technical aspects of cryptography and coding are solicited for submission. The proceedings will be published in [[http://www.springer.com/lncs][Springer’s Lecture]] [[http://www.springer.com/lncs][Notes in Computer Science]] series, and will be available at the conference.

*** Important Dates

| Submission Deadline          | 14 July 2017          |
| Author Notification          | 5 September 2017      |
| Proceedings Version Deadline | 22 September 2017     |
| Conference                   | 12 – 14 December 2017 |

*** Instructions for Authors

Submissions must not substantially duplicate work that any of the authors has published elsewhere or has submitted in parallel to a journal or any other conference or workshop with proceedings. Accepted submissions may not appear in any other conference or workshop that has proceedings. Authors of accepted papers must guarantee that their paper will be presented at the conference and must make a full version of their paper available online.

All submissions will be blind-reviewed. Papers must be anonymous, with no author names, affiliations, acknowledgements, or obvious references. Submissions should begin with a cover page containing title, a short abstract, and a list of keywords. The body of the paper should be at most 14 pages, excluding the title page with abstract, the bibliography, and clearly marked appendices. Committee members are not required to review appendices, so the paper should be intelligible and self-contained within this length. The text should be in a single column format, in at least 11-point fonts and have reasonable margins. Submissions not meeting these guidelines risk rejection without consideration of their merits.

*** Programme and Organising Committee

- Máire O’Neill, Queen’s University Belfast (Chair)
- Liqun Chen, University of Surrey
- Bahram Honary, University of Lancaster
- Christopher Mitchell, Royal Holloway University of London
- Matthew Parker, University of Bergen
- Kenneth Paterson, Royal Holloway University of London
- Fred Piper, Royal Holloway University of London
- Martijn Stam, University of Bristol
- Martin Albrecht, Royal Holloway, University of London, UK
- Marco Baldi, Università Politecnica delle Marche, Italy
- Mohammed Benaissa, University of Sheffield
- Claude Carlet, University of Paris 8, LAGA, France
- Dooho Choi, ETRI, S.Korea
- Marten van Dijk, University of Connecticut, US
- Pooya Farshim, Queen’s University Belfast, UK
- Philippe Gaborit, University of Limoges, France
- Guang Gong, University of Waterloo, Canada
- Jens Groth, University College London, UK (Chair)
- Cong Ling, Imperial College London, UK
- Helger Lipmaa, University of Tartu, Estonia
- Subhamoy Maitra, Indian Statistical Institute, India
- Atsuko Miyaji, Japan Advanced Institute of Science and Technology, Japan
- Elizabeth O’Sullivan, Queen’s University Belfast
- Carles Padró, Universitat Politècnica de Catalunya, Spain
- Raphael Phan, Multimedia University, Malaysia
- Joachim Rosenthal, University of Zurich, Switzerland
- Rei Safavi-Naini, University of Calgary, Canada
- Ana Sălăgean, Loughborough University, UK
- Fre Vercauteren, KU Leuven, Belgium
- Adrian Waller, Thales, UK
- Chapoing Xing, Nanyang Technological University, Singapore
