#+TITLE: Final Version of my PhD thesis
#+POSTID: 230
#+DATE: [2010-10-11 Mon 13:27]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: m4ri, sage
#+TAGS: algebraic attacks, algebraic cryptanalysis, cold boot attacks, commutative algebra, cryptography, f5, linear algebra, m4ri, matrix decomposition, max-posso, mixed integer programming, present cipher, sage, thesis

I passed my PhD defence on Friday. I've uploaded the final version of my thesis titled [[http://martinralbrecht.files.wordpress.com/2010/10/phd.pdf][Algorithmic Algebraic Techniques and their Application to Block Cipher Cryptanalysis]]. Not much changed since the last draft, which I also posted on this blog, except a few typos and errors.

 Btw. here's the abstract of the thesis:

#+BEGIN_QUOTE
In Part I we present and discuss implementations of both well-known and novel algorithms for fundamental problems of linear algebra over the field with two elements (F2). In particular, we present the best known implementations for matrix-matrix multiplication and matrix decomposition for dense matrices over F2. These implementations are based on novel variants of the "M4RM" multiplication algorithm and the M4RI elimination algorithm.

In Part II we discuss Gröbner basis algorithms. No algorithm discussed in this part is new. However, we are not aware of any other treatment of either the matrix-F5 or the F4-style F5 in the English speaking literature which covers these algorithms in such detail. Furthermore, we provide reference implementations for all algorithms discussed in this part.

In Part III we apply algebraic techniques to the cryptanalysis of block ciphers. The key contributions of this part are novel ways of utilising algebraic techniques in cryptanalysis. In particular, we combine algebraic techniques with linear, differential and higher-order differential cryptanalysis. These hybrid approaches allow us to push the respective cryptanalytical technique further in most cases. We also explicitly shift the focus from solving polynomial systems of equations to computing features about block ciphers which can then be used in other attacks. Finally, we propose a new family of problems - denoted "Max-PoSSo" in this thesis - which model polynomial system solving with noise. We also propose an algorithm for solving these problems, based on Integer Programming, and apply this algorithm to the so-called "Cold Boot" problem.
#+END_QUOTE

Finally, I've also uploaded the [[http://martinralbrecht.files.wordpress.com/2010/10/viva.pdf][slides]] I've made for my defence which are in a way an extended abstract.



