#+BLOG: martinralbrecht
#+POSTID: 1246
#+DATE: [2016-02-19 Fri 19:02]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: cryptography
#+TAGS:fplll, crypto, sage, workshop
#+DESCRIPTION:
#+TITLE: fplll days 1
We’ll have a [[https://github.com/dstehle/fplll/wiki/fplll-days-1][first fplll coding sprint]] aka “fplll days” from June 20 to June 24 at ENS Lyon.

The idea of [[https://github.com/dstehle/fplll][fplll]] days is inspired by and might follow the format of [[https://wiki.sagemath.org/Workshops][Sage Days]] which are semi-regularly organised by the [[http://sagemath.org][SageMath]] community. The idea is simply to get a bunch of motivated developers in a room to work on code. Judging from experience in the SageMath community, lots of interesting projects get started and completed.

We intend to combine the coding sprint with the lattice meeting (to be confirmed), so we’d be looking at 3 days of coding plus 2 days of regular lattice meeting. We might organise one talk per coding day, to give people a reason to gather at a given time of the day, but the focus would be very much on working on fplll together.

If you'd like to attend, please send an e-mail to one of the maintainers e.g. me.
