#+TITLE: Mesh Messaging in Large-scale Protests: Breaking Bridgefy
#+BLOG: martinralbrecht
#+POSTID: 1846
#+DATE: [2020-08-24 Mon 13:00]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: cryptography
#+TAGS: cryptography, bridgefy, protests, cryptanalysis, it-security
#+DESCRIPTION:

Together with [[https://www.jorgeblascoalis.com/][Jorge Blasco]], [[https://pure.royalholloway.ac.uk/portal/en/persons/rikke-bjerg-jensen(21f74e0b-9a6e-47fb-9889-9f9a1f5cf2a4).html][Rikke Bjerg Jensen]] and [[https://pure.royalholloway.ac.uk/portal/en/persons/lenka-marekova(371a2632-c1c4-4866-8141-c4b99807d326).html][Lenka Marekova]] we have studied the security of the [[https://bridgefy.me/][Bridgefy]] mesh messaging application. This work was motivated by (social) media reports that this application was or is used by participants in large-scale protests in anticipation of or in response to government-mandated Internet shutdowns (or simply because the network infrastructure cannot handle as many devices at the same time as there are during such large protests). The first reports were about [[https://www.forbes.com/sites/thomasbrewster/2019/09/04/hong-kong-protesters-are-using-this-mesh-messaging-app--but-should-they-trust-it/][Hong Kong]], later reports were then about [[https://www.scmp.com/week-asia/politics/article/3042633/whatsapp-bridgefy-what-hong-kong-taught-indias-leaderless][India]], [[https://www.fastcompany.com/90470779/how-the-internet-shutdown-in-kashmir-is-splintering-indias-democracy][Iran]], [[https://twitter.com/bridgefy/status/1268015807252004864][US]], [[https://twitter.com/wamagaisa/status/1288817111796797440][Zimbabwe]], [[https://twitter.com/bridgefy/status/1292880821725036545][Belarus]] and [[https://twitter.com/B1O15J/status/1294603355277336576][Thailand]] (typically referencing Hong Kong as an inspiration). In such a situation, [[https://en.wikipedia.org/wiki/Mesh_network][mesh networking]] seems promising: a network is spanned between participants’ phones to create an ad-hoc local network to route messages.

Now, Bridgefy wasn’t designed with this use-case in mind. Rather, its designers had large sports events or natural disasters in mind. Leaving aside the discussion here if those use-cases too warrant a secure-by-default design, we had reason to suspect that the security offered by Bridgefy might not match the expectation of those who might rely on it.

Indeed, we found a series of vulnerabilities in Bridgefy. Our results show that Bridgefy currently permits its users to be tracked, offers no authenticity, no effective confidentiality protections and lacks resilience against adversarially crafted messages. We verify these vulnerabilities by demonstrating a series of practical attacks on Bridgefy. Thus, if protesters rely on Bridgefy, an adversary can produce social graphs about them, read their messages, impersonate anyone to anyone and shut down the entire network with a single maliciously crafted message. For a good overview, see [[https://arstechnica.com/author/dan-goodin/][Dan Goodin]]’s [[https://arstechnica.com/features/2020/08/bridgefy-the-app-promoted-for-mass-protests-is-a-privacy-disaster/][article]] on our work at [[https://arstechnica.com/][Ars Technica]].

We disclosed these vulnerabilities to the Bridgefy developers in April 2020 and agreed on a public disclosure date of 20 August 2020. Starting from 1 June 2020, the Bridgefy team began warning their users that they should not expect confidentiality guarantees from the current version of the application.

Let me stress, however, that, as of 24 August, Bridgefy has not been patched to fix these vulnerabilities and thus that these vulnerabilities are present in the currently deployed version. The developers are currently implementing/testing a switch to the [[https://en.wikipedia.org/wiki/Signal_Protocol][Signal protocol]] to provide cryptographic assurances in their SDK. This switch, if done correctly, would rule out many of the attacks described in our work. They hope to have this fix deployed soon.

#+HTML:<!--more-->

We decided to publish an [[https://martinralbrecht.files.wordpress.com/2020/08/bridgefy-abridged.pdf][abridged version]] of our work – leaving out some technical details about how Bridgefy processes messages – today to draw greater attention to the ongoing risks posed by running the application in its current version. That is, participants of protests should avoid relying on Bridgefy until these vulnerabilities are addressed.

More meta, this work is part of a larger (dare I say: interdisciplinary) endeavour in the [[https://www.royalholloway.ac.uk/research-and-teaching/departments-and-schools/information-security/][Information Security Group]] to study the (digital) security needs of participants in large-scale protests. Jorge is in the [[https://s3lab.isg.rhul.ac.uk/][Systems & Software Security Lab]], Rikke is an [[https://www.amazon.co.uk/Ethnography-Principles-Practice-Martyn-Hammersley/dp/0415396050][ethnographer]] and Lenka and I are cryptographers. Rikke and I [[https://martinralbrecht.wordpress.com/2020/07/10/what-does-secure-mean-in-information-security/][wrote up]] our motivations/thinking in a piece for the [[https://royalholloway.ac.uk/media/13586/isg-newsletter-2019-20.pdf][ISG Newsletter]] recently.
