#+TITLE: Postdoc position in Cryptology at DTU
#+POSTID: 1020
#+DATE: [2014-01-27 Mon 13:10]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: cryptography
#+TAGS: cryptography, dtu, job, postdoc

DTU has a postdoc position [[http://www.dtu.dk/english/career/job?id=75ce13d3-7f72-4e8c-b508-8d56749f53df][available]] in the crypto group. I can highly recommend working there.

#+BEGIN_QUOTE
  [[http://www.dtu.dk/english/career/job?id=75ce13d3-7f72-4e8c-b508-8d56749f53df#][*Apply no later than 15 March 2014*]]

Apply for the job at DTU Compute by completing the following form.
  
[[http://www.compute.dtu.dk/english][Department of Applied Mathematics and Computer Science]], Technical University of Denmark, would like to invite applications for a Postdoc position of 18 months, starting 1 April 2014 or soon thereafter.

The topic of the project is lightweight cryptology, which regards scenarios involving strongly resource-constrained devices.

*Qualifications*
Candidates for the position should have a solid background in hardware design and automation and be able to work on the physical constraints and optimization of the hardware implementations or, alternatively, we will consider candidates with a strong cryptanalytic and mathematical background who are able to analyse the security of ciphers to be designed.

All candidates must have a PhD degree in applied mathematics, computer science, or engineering or academic qualifications equivalent to the PhD degree in engineering and they should have demonstrated qualifications in cryptology. The candidate must be well versed in written and spoken English.

*We offer*
We offer an interesting and challenging job in an international environment focusing on education, research, public-sector consultancy and innovation, which contribute to enhancing the economy and improving social welfare. We strive for academic excellence, collegial respect and freedom tempered by responsibility. The Technical University of Denmark (DTU) is a leading technical university in northern Europe and benchmarks with the best universities in the world.

*Salary and terms of appointment
*The Danish Research Council finances the positions. The appointment will be based on the collective agreement with the Confederation of Professional Associations. The allowance will be agreed with the relevant union.

*Further Information
*Further information can be obtained from Professor Lars R. Knudsen, DTU Compute, e-mail: [[mailto:lrkn@dtu.dk][lrkn@dtu.dk]].

You can read more about DTU Compute on [[http://www.compute.dtu.dk/english][www.compute.dtu.dk/english]].

*Application procedure
*Please submit your online application no later than *15 March 2014.* Applications must be submitted as *one PDF file* containing all materials to be given consideration. To apply, please open the link "Apply online," fill in the online application form, and *attach all your materials in English in one PDF file*. The file must include:


  -  Application (cover letter)
  -  CV
  -  Diploma
  -  List of publications
#+END_QUOTE



