#+TITLE: Reading Material on Gender Essentialism
#+BLOG: martinralbrecht
#+CATEGORY: misc
#+TAGS: gender
#+POSTID: 1424
#+DATE: [2017-08-12 Sat 21:16]

In a memo titled [[https://diversitymemo.com][Google’s Ideological Echo Chamber]] James Damore claims that “the distribution of preferences and abilities of men and women differ in part due to biological causes and that these differences may explain why we don’t see equal representation of women in tech and leadership” with the aim to show that “discrimination to reach equal representation is unfair, divisive, and bad for business.” Soon after the memo went viral, tech sites such as Hacker News started to see [[http://quillette.com/2017/08/07/google-memo-four-scientists-respond/][supportive]] [[https://ifstudies.org/blog/straight-talk-about-sex-differences-in-occupational-choices-and-work-family-tradeoffs][statements]]. Motherboard [[https://motherboard.vice.com/en_us/article/ywpamw/internal-reaction-to-google-employees-manifesto-show-anti-diversity-views-have-support][reports]] that the verdicts expressed in the memo have some traction amongst the author’s former co-workers. It stands to reason that this agreement is not the privilege of Google employees, or as [[http://blog.alicegoldfuss.com][Alice Goldfuss]] put it:


#+BEGIN_QUOTE
I’ve read the Google anti-diversity screed and you should, too. You meaning men. Women have heard this shit before. Why should men read it? Because it's a 10 page essay that eloquently tears away the humanity of women and non-white men. It uses bullet points and proper spelling and sounds very calm and convincing. And it should, because it was written by one of your peers.

— Alice Goldfuss (@alicegoldfuss) [[https://twitter.com/alicegoldfuss/status/893961445934645248][August 5, 2017]]
#+END_QUOTE

While I do not work in (US) “tech” (I’m an academic cryptographer at a British university), I guess the fields are close enough. Besides, gender essentialism is a prevalent idea beyond the confines of STEM disciplines. As mentioned above, the memo offers a bullet point list to support its claim:

#+BEGIN_QUOTE
1. [The differences between men and women] are universal across human cultures
2. They often have clear biological causes and links to prenatal testosterone
3. Biological males that were castrated at birth and raised as females often still identify and act like males
4. The underlying traits are highly heritable
5. They’re exactly what we would predict from an evolutionary psychology perspective
#+END_QUOTE

The memo and its defenders accuse those who disagree with its claims as being ideologically driven moralists[fn:1], hence the memo’s title. Alas, since I read several [[https://www.vox.com/the-big-idea/2017/8/11/16130452/google-memo-women-tech-biology-sexism][good]] [[http://www.reviewerthree.com/2017/08/lets-talk-about-sex-baby.html][critiques]] and their source material over the last few days, I figured I might attempt to summarise some of these arguments.[fn:2] Initially, my plan was to simply dump a list of books and articles here, but reading around as someone not so familiar with this literature, I found this mode of presentation (“well, my meta-study says your meta-study is full of it”) rather unhelpful. Thus, I opted for spelling out in more detail which arguments I found particularly illuminating.[fn:3] 


#+HTML:<!--more-->

* “Clear biological causes and links to prenatal testosterone”

[[http://www.hup.harvard.edu/catalog.php?isbn=9780674063518&content=reviews][Brain Storm - The Flaws in the Science of Sex Differences]] by Rebecca M. Jordan-Young (I encountered it [[https://www.recode.net/2017/8/11/16127992/google-engineer-memo-research-science-women-biology-tech-james-damore][here]]) examines and discusses brain organisation research which explains behavioural differences between men and women through the effects of sex hormones.[fn:4] Indeed, there is a huge body of work, where each individual paper would agree with the statement of “clear biological causes and links to prenatal testosterone”, as pointed out by various defenders of the memo. However, as Jordan-Young shows in great detail, this does not justify the conclusion:

#+BEGIN_QUOTE
For example, consider a set of studies that look at testosterone exposures within certain, defined exposure periods (say first versus second versus third trimester of pregnancy). Imagine that one study finds testosterone exposure relates to spatial abilities, but only exposures during the first trimester, and a second study finds that only testosterone exposures during the third trimester relate to spatial abilities. These studies are not, in fact, symmetrical. This is particularly important when studies test a great many relationships, as is the norm in brain organization research, because the higher the number of relationships tested, the greater the odds that some relationships will be “statistically significant” only by chance (this issue is raised for a number of specific studies in the chapters that follow).
#+END_QUOTE

Just because two studies claim to have found some connection between testosterone levels and, say, spatial abilities, this does not mean that they agree on the identified causes. The two studies might very well contradict each other and thus it is not sound to add them up to form a conclusion of the form “many studies have shown”. There is a difference between the respective study’s claim to have found a /particular/ causal relation and the political point made by Damore et al. that there is /some/ causal relation. The programme of Jordan-Young’s book is to make clear that the brain organisation literature is rife with contradictions of this kind.[fn:5]

These contradictions do not only exist with respect to causes but also, and perhaps more importantly, with respect to effects. A key issue with these studies drawn out by Jordan-Young is the disconnect between what they are trying to establish — “the differences between men and women due to prenatal hormones” — and what they are actually testing, i.e. some particular set of observed or reported behaviours. Now, “typical male” and “typical female” behaviour are vague terms and at the very least should be clearly defined. Yet, these definitions are largely considered “common sense” in the respective studies (and by the respective scientists interviewed by Jordan-Young). Thus, these definitions are not explicit in the respective studies and Jordan-Young shows how these different “common sense” definitions contradict each other. That is, “typical female” behaviour in one study is coded as “typical male” behaviour in another study. Libido is a good example: earlier studies asserted typical female behaviour as coyness and as having an almost exclusively romantic interest in sex, whereas later studies considered a low desire for heterosexual intercourse as atypical female behaviour. Then, since male/female behaviour is often still modelled as poles of a continuum, atypical female behaviour is coded as male:

#+BEGIN_QUOTE
In his publications on a sample of German women with [[https://rarediseases.org/rare-diseases/congenital-adrenal-hyperplasia/][CAH]] (especially Dittmann, Kappes, and Kappes 1992), Dittmann characterized women with CAH as “masculinized” in comparison to their nonaffected sisters. While the scientists’ interpretation of “normal” feminine sexuality in these sisters includes many features that have been characterized as feminine since early brain organization research (being in love, having long-term relationships with partners, and especially being attracted only to men), it also quite remarkably includes many features that were always characterized as masculine in the early studies. The sisters with presumably “feminine” prenatal hormone histories report /more/ initiation of sexual relationships, /more/ sexual contacts, /more/ orgasmic experiences, and /more/ romantic/erotic night dreams than the “masculinized” women with CAH. Yet all of these differences are presented as indication of “feminine” sexuality and taken to support the brain organization hypothesis! Similarly, more recent analyses of sexual functioning and sexual activity in women with CAH either present lower levels of sexual arousal, masturbation, and heterosexual intercourse as “apart from” those aspects of psychosexuality that would be affected by early androgens (Kuhnle et al. 1993), or they include the suggestion or explicit interpretation that lower levels of arousal, masturbation, and heterosexual activity may reflect brain masculinization (Federman 1987; Mulaikal, Migeon, and Rock 1987; Zucker et al. 1996; Meyer-Bahlburg 1999; Zucker et al. 2004).
#+END_QUOTE

The point here is not only that different studies have different or contradictory ideas of typical male/female behaviour and thus do not constitute a body of work which can be referenced together to support a claim, but also that scientists inscribed the respective mores of their societies and their own presumptions about what male/female means into their studies. Jordan-Young gives another example of a study by Gerianne M Alexander and Melissa Hines which attempted to show that gender specific “toy preferences may be associated with factors other than human social and cognitive development” by studying vervet monkey babies. The study concluded: “This implies that sexually dimorphic preferences for features (e.g., color, shape, movement) may have evolved from differential selection pressures based on the different behavioural roles of males and females, and that evolved object feature preferences may contribute to present day sexually dimorphic toy preferences in children.” Jordan-Young criticises this conclusion:

#+BEGIN_QUOTE
Now return to Alexander and Hines’s explanation for their results. How could these items have differential “functional significance” for male versus female vervets? Certainly vervets aren’t practicing future gender roles when they play with cooking pots or police cars. To address this obvious problem, Alexander and Hines argue that “the primate brain has evolved specialized recognition systems for categories with adaptive significance, such as emotional expressions and facial identity” (474). But these features would apply to both the “female-coded” doll and the “neutral” plush dog. Noting that there were no sex differences in preference for “toy categories based on an animate-like (doll, dog) or inanimate-like (car, ball, book, pan) distinction” (474), Alexander and Hines appeal to color to explain why the female vervets spent proportionately more of their time than the males did in contact with the doll and the cooking pot: the doll face is pink, and the pot is red. This is misleading, though, because the female vervets spent slightly more time with the (nonpink, nonred) dog than they did with the pink-faced doll.

The same shortcoming is apparent in their explanation of the male vervets’ behavior. Reasoning that so-called boys’ toys like the ball and the car are “objects with an ability to be used actively,” Alexander and Hines speculate that these objects “afford greater opportunities for engaging in rough or active play” (475). The male vervets “favorite” toy—by a wide margin—was the plush dog, a toy that does not apparently lend itself to rough or active play. And let’s not forget that the (boyish) police car was roughly tied in contact time with the (girlish) cooking pot. Finally, it would be extremely useful to see what the vervets actually did with the various toys. How does a vervet know that the purpose of a cooking pot is not to bang it, throw it, or use it to whack another vervet? Only by knowing the human purposes of these objects can we sort them into categories that seem to objectively reflect an “ability to be used actively.”
#+END_QUOTE

A key example for the disconnect between what is being measured or observed and what is interpreted is a study by Jennifer Connellan and Simon Baron-Cohen. This study and its interpretation in Cohen’s book is where the “things/systemising” vs “people/emphasising” opposition comes from that is referenced in the memo.[fn:6] In this study, female and male babies were shown, side by side, a smiling person or a mobile (a hanging ball painted with human eyes in the wrong position). Boys looked longer at the mobile, girls on average longer at the face.[fn:7] The study has not be reproduced and similar studies did not confirm its findings (cf. /Brain Storm/ or [[https://www.amazon.co.uk/d/cka/Living-Dolls-Return-Sexism-Natasha-Walter/1844087093][Living Dolls]] by Natasha Walter), but what struck me is how casual the interpretation leap is as pointed out in /Living Dolls/: looking at an object for longer does not necessarily imply interest and looking at a face resp. some abstract art — without any notions of what these mean — does not map to “people/emphasising”, on the one hand, and “things/systemising”, on the other.

The malleability of the “things/people” pair is nicely illustrated by a quote from [[https://ifstudies.org/blog/straight-talk-about-sex-differences-in-occupational-choices-and-work-family-tradeoffs][David C. Gery]] in support of claims in the memo: “On the other hand, individuals with an interest /in people/ gravitate to fields that involve working with living things, which is one reason why women who are interested in science are much more likely to pursue a career in biology or veterinary medicine than computer science.”; plants are people. Elsewhere, the category “people” is [[http://slatestarcodex.com/2017/08/07/contra-grant-on-exaggerated-differences/][stretched]] to encompass female roles “to include communities, talking, helping, children, and animals” and “things” to “include both physical objects like machines as well as complex abstract systems”. In other words, these categories are redefined to match presumed typical male/female roles to then discover that these categories capture typical male/female roles. Jordan-Young comments on the “systemising” category of Baron-Cohen:

#+BEGIN_QUOTE
A difficulty in characterizing Baron-Cohen’s work is the fuzziness of the conceptual category “systems.” In measurement terms, the idea that systems comprise “phenomena that are … lawful, finite, and deterministic” does not act as a sensitive and specific guide to the sorts of interests that he classifies, in practice, as masculine. Does the law comprise a “lawful” system? If so, what do we make of the rapid change in this field from one where men dominated for centuries, to one where there is now slight female dominance in new practitioners? Accounting provides another example. Surely accountants deal with “systems” that are “lawful, finite, and deterministic.” But Wootton and Kemmerer (2000) document that “the gender composition of the accounting profession changed from 10% female in 1930 to 53% female by 1990.”
#+END_QUOTE

The logic of the memo and the research it relies on seems to be roughly this: human activity is divided into two classes, say, related to circles and related to angular shapes. Presumed typical activities are coded as “circle-related” (cooking pots are round, the cycle of life, society is like a circle of people, when people talk they sit in a circle, faces of kind of round) and presumed male activities are coded as “angular“ (aggression, straight lines in engineering, office desks have edges, hierarchies are triangular, …); pick your favourite gender stereotype and fit it in. Then, the reason why people from different genders engage in the respective activities (more or less) is attributed to their (biological) affinity towards circular and angular shapes, i.e. the particular reasons they have for each particular activity are put aside. In a next step, a proof is then attempted that this affinity towards circular/angular shapes is innate: experiments are conducted where babies, say which had some unusual prenatal hormone exposure, are observed whether they, say, look more at the plates (circles) or out the window (a square). The finding is then not simply interpreted as e.g. “increased testosterone levels lead to a preference for windows” (leaving aside all questions of sound study design and replication) but as “increased levels of testosterone lead to a preference for male square-like activities, these are thus established as innate.” A later study confirms the general conclusion by reporting that some babies looked more out of the window towards the clouds (kind of round) instead of the square table.

* “What we would predict from an evolutionary psychology perspective”

Besides the already mentioned /Living Dolls/ book by Natasha Walter, I found [[http://econtent.hogrefe.com/doi/abs/10.1027/1901-2276/a000039?journalCode=nop][Can We Save Darwin from Evolutionary Psychology?]] by Svend Brinkmann quite illuminating (which I came across [[https://gizmodo.com/men-have-always-used-science-to-explain-why-theyre-bett-1797608461][here]]). The latter draws heavily on [[https://www.penguin.co.uk/books/1033282/alas-poor-darwin/][Alas, Poor Darwin]] edited by Hilary Rose and Steven Rose.[fn:8] Recounting the five tenets of evolutionary psychology as outlined in “Evolutionary psychology: A primer” by Leda Cosmides and John Tooby, Brinkmann provides a succinct critique. Based on the aforementioned texts and the examples from the evolutionary psychology literature I read, evolutionary psychology claims that the way we think (they’d say “our mind” or “our brain”) was “designed” for the challenges of the Pleistocene by natural selection, i.e. adaptations with the aim of producing many offsprings.[fn:9] Brinkmann summarises:

#+BEGIN_QUOTE
We have Stone Age or Pleistocene minds, they say, but live in the twenty-first century, and this allegedly explains a host of human doings and sufferings today, ranging from rape to the stress epidemic. The very idea that the structure (or “architecture”, to use the favored expression of evolutionary psychologists) of the mind was fixed during the Pleistocene is curious, for, as Hilary Rose (a sociologist) and Steven Rose (a neurobiologist) point out (2000, p. 2), we know that non-human animals can evolve significantly through natural selection (not to speak of artificial selection as in breeding) in the course of just a few decades, e.g. the finches studied in Darwin’s own Galapagos that develop new shapes of beaks and feeding habits very quickly in response to climate changes, so why not humans? Furthermore, we know very little about what life was like 100,000 years ago. Anthropologists have found shards of bones and a few bodies, but there is substantial disagreement even at the level of establishing the sex of Lucy, the early hominid discovered in 1974 in Ethiopia (H. Rose, 2000, p. 118). In light of this (unsurprising) lack of evidence about life in the Pleistocene, it seems quite speculative to use this period, and how “neural circuits were designed by natural selection” during the period, to explain purportedly universal cultural practices to do with the age difference in marriage between men and women or female beauty, to cite just some of the well-known arguments of evolutionary psychologists (p. 117). We simply do not know in sufficient detail which problems our ancestors faced.
#+END_QUOTE

The innovation of evolutionary psychology compared to its predecessor sociobiology is that it allows for behaviour to be disfunctional now (in a natural selection sense) since we were programmed in the Pleistocene. Stephen Jay Gould in /More Things in Heaven and Earth/ in /Alas, Poor Darwin/ comments:

#+BEGIN_QUOTE
To take an illustration proposed seriously by Robert Wright in /The Moral Animal/, a sweet tooth leads to unhealthy obesity today but must have arisen as an adaptation. Wright therefore states, “The classic example of an adaptation that has outlived its logic is the sweet tooth. Our fondness for sweetness was designed for an environment in which fruit existed but candy didn’t.“
This statement ranks as pure guesswork in the cocktail party mode; Wright presents no neurological evidence of a brain module for sweetness and no palaeontological data about ancestral feeding. This ‘Just-so story’ therefore cannot stand as a “classic example of an adaptation” in any sense deserving the name of science.
#+END_QUOTE

As mentioned by Gould above, a key principle of evolutionary psychology is that the “human mind” is, by design, a Swiss-army knife of many “modules”; examples of these modules are a generic language processing module, a cheat detection module etc. This modular notion of the mind might seem to be common sense insofar as MRI scans where different areas of the brain light up during certain mental activities are popular in the media, but Brinkmann points out that these scans are from adults and brain areas show a great deal of plasticity during development:

#+BEGIN_QUOTE
Babies’ brains are not Swiss army knives, and this very image rests on the false dichotomy of evolution (phylogeny) and ontogeny. If there is brain specialization, it is actually the product of child development (within the relevant biological and social contexts) rather than its starting point (p. 147).
#+END_QUOTE

Secondly, the notion of modules in evolutionary psychology does not make itself dependent on actually observed brain activity, rather these modules are speculatively arrived at, as Steve Rose explains in /Alas, Poor Darwin/:

#+BEGIN_QUOTE
Whether such modules are more than theoretical entities is unclear, at least to most neuroscientists. Indeed evolutionary psychologists such as Pinker go to some lengths to make it clear that the “mental modules” they invent do not, or at least do not necessarily, map on to specific brain structures. (In this sense they are rather like Dawkins’s theoretical genes.)
#+END_QUOTE 

The memo makes positive references to both evolutionary psychology and IQ theory,[fn:10] but these are incompatible as Steve Rose explains:

#+BEGIN_QUOTE
The insistence of evolutionary psychology theorists on modularity puts a particular strain on their otherwise heaven-made alliance with behaviour geneticists. For instance, IQ theorists, such as the psychometrician Robert Plomin, are committed to the view that intelligence, far from being modular, can be reduced to a single underlying factor, /g/, or ‘crystallised intelligence’. A similar position has emphatically been taken in recent years by Herrnstein and Murray in /The Bell Curve/, who argue that whatever intelligence is, it cannot be dissociated into modules!
#+END_QUOTE

Where IQ theory claims a unit of intelligence /g/, evolutionary psychology claims that some ability A is completely dissociated from some other ability B. The contradiction between these two theories being ignored by the memo highlights the differences between what /particular/ theories claim to have established and the political desire that is content with /any/ differences to exist in order to argue against a certain set of social policies. In this view, the particular explanatory power of the various theories being grouped together and their contradictions are of secondary importance. Put differently, the memo does not seem to draw conclusions from, perhaps flawed, scientific results, but seeks scientific studies that can be used to support its political aims.[fn:11]

Towards the end, Brickmann lays out the Catch-22 for any theory which attempts to explain thinking as a process /determined/ by other factors than reason:

#+BEGIN_QUOTE
evolutionary psychology risks undermining itself if it argues that human normative capacities (such as our powers of reasoning, judgment and morality) are what they are, only because they have been selected for. As Nagel (1997) points out, such reductive strategies collapse if the claim is made that whatever we have reason to believe (morally, logically etc.) is the result of our psychological apparatus as a response to evolutionary adaptation. For if the evolutionary reductionists want to remain consistent, this must also apply to the theory itself! On this evolutionary account, therefore, the only reason I could have to believe this account itself would be grounded in natural selection. Thus, if the evolutionary hypothesis itself depends on reason, and if reason is a product of natural selection, then the hypothesis is self-undermining. There must be something more than simply being a product of natural selection to human perception, thinking, and reasoning if we are to trust these capacities. As Nagel says: “I can have no justification for trusting a reasoning capacity I have as a consequence of natural selection, unless I am justified in trusting it simply in itself – that is, believing what it tells me, in virtue of the content of the arguments it delivers.” (p. 136)
#+END_QUOTE

/Insofar/ as a theory argues that our mental capacities are beyond the realm of reason, e.g. that interests and abilities are naturally predetermined, it runs into problems accounting for itself: did some predisposition lead to its discovery/inception, is it only plausible to its proponents because of some evolutionary pressure? How do you scientifically prove that, fundamentally science isn’t possible because we are prisoners of our natural predisposition? On the same note, Steven Rose writes in /Alas, Poor Darwin/:

#+BEGIN_QUOTE
There is an ultimate contradiction at the core of evolutionary psychology theory. Whatever the claimed evolutionary honing of our every intention and act, evolutionary psychologists remain anxious to insist on at least their own autonomy. “If my genes don’t like it,” says Pinker, “they can go jump in the lake.” Rather less demotically, Dawkins insists that only we as humans have the power to rebel against the tyranny of the selfish replicators. Such a claim to a Cartesian separation of these authors’ minds from their biological constitution and inheritance seems surprising and incompatible with their claimed materialism. Where does this strange free will come from in a genetically and evolutionarily determined universe?

The problem is indicated even sharply by the reprinting of a series of classical anthropological and sociobiological papers in the collection entitled /Human Nature/. The editor’s view is that these show the way that Darwinian insights transform our understanding of social organisation. The papers were largely published in the 1970s and 1980s, and, for their republication in 1997, each author was asked to reflect in retrospect on their findings. What is interesting is that when the anthropologists go back to their field subjects, they report rapid changes in their styles of living. Kipsigis women no longer prefer wealthy men (Borgerhoff, Mulder), the Yanonomo are no longer as violent as in the past (Chagnon), wealth no longer predicts the number of children reared (Gaulin and Boster) and so forth. Each of these societies has undergone rapid economic, technological and social change in the last decade. What has happened to the evolutionary psychology predictions? Why have these assumed human universals suddenly failed to operate? Has there been a sudden increase in mutation rates? Have the peoples they had studied taken Dawkins to heart and decided to rebel against the tyranny of their selfish replicators?
#+END_QUOTE

* “Universal across human cultures”

The claim of the memo that differences are statistically robustly observable seems to have received the most attention, e.g. [[https://heterodoxacademy.org/2017/08/10/the-google-memo-what-does-the-research-say-about-gender-differences/][here]], [[https://www.linkedin.com/pulse/differences-between-men-women-vastly-exaggerated-adam-grant][here]] and [[http://slatestarcodex.com/2017/08/07/contra-grant-on-exaggerated-differences/][here]]. However, statistically observing these differences does not in itself offer an explanation and is not meant as such. Instead, in the memo these observations are taken as evidence for innate differences (either in ability as in the memo or, more commonly in the literature, interest).

In particular, the memo argues that gender differences are innate because they are reportedly bigger in more gender-equal societies.[fn:12] David C. Geary, [[https://ifstudies.org/blog/straight-talk-about-sex-differences-in-occupational-choices-and-work-family-tradeoffs][seemingly supporting the claim]], explains that, for example, in Finland girls outperform boys in science in school. On the other hand, fewer women than men obtain STEM university degrees in Finland, [[http://www.catalyst.org/knowledge/women-science-technology-engineering-and-mathematics-stem][21.5%]] in 2014 (compared to 25.6% in France, 22.4% in the UK, 19.3% in Germany, but [[http://slatestarcodex.com/2017/08/07/contra-grant-on-exaggerated-differences/][55% in Thailand]], 54% in Guyana, 51% in Malaysia, 41% in Iran and Zimbabwe). He then reports that while girls in Finland outperform boys in science, they do on average even better in reading, while boys perform relatively better in maths/science than reading. He interprets this as: “One of the luxuries of living in one of these societies is the opportunity to explore and pursue occupational niches that not only fit your interests but also your academic (and other, such as interpersonal) strengths”. It is not clear to me what the status of this explanation is in Geary’s piece. On the one hand, he earlier speculates about evolutionary pressure for men to build weapons in an evolutionary psychology manner. On the other hand, he does not directly invoke biology when discussing this Finish example, so he might not agree with the memo on this particular point. Insofar it is meant to support the innate interpretation, this would be curious: did the gender-equal Finish society finally liberate girls from the pressure /towards/ maths and science, subjects that the memo and others keep telling us women are predisposed against? The only way I can see how one would arrive at the innate conclusion from the presented data is to start from the premise that the relative school performance in reading vs maths for teenagers is innate, i.e. the conclusion would be in the premise. 

However, applying the caution about empty abstractions from above here, my key take-away would be this: Having already reduced the various typical male/female activities to “thing”/“people” orientations, the argument then also relies on reducing the differences between societies to more or less gender-equal by some measure. For example, Zimbabwe and Finland are not only distinguished by the respective gender mores but also by, e.g. their economy. This informs, for example, what career choices people have and who the people are having these career choices. This /might/ explain why CS statistics are relatively similar in successful capitalist countries, but rather different in countries with less success in international competition. Of course, this is speculation on my part, the point here is merely to offer some other explanation to highlight the leap. But rather than trying to speculate about the motives of Finish boys, girls, men, women and everybody else, there is another option: they are human beings who have particular interests and particular reasons, we can learn these by asking them.[fn:13]

* Footnotes

[fn:1] The memo gives a curious account of the genesis of the opposing viewpoint: “Communism promised to be both morally and economically superior to capitalism, but every attempt became morally corrupt and an economic failure. As it became clear that the working class of the liberal democracies wasn’t going to overthrow their ’capitalist oppressors,’ the Marxist intellectuals transitioned from class warfare to gender and race politics. The core oppressor-oppressed dynamics remained, but now the oppressor is the ’white, straight, cis-gendered patriarchy.’” As far as US conservatives are concerned, Marxism is having a field day in the upper echelons of US corporations.

[fn:2] Btw. I recommend Cynthia Lee’s [[https://www.vox.com/the-big-idea/2017/8/11/16130452/google-memo-women-tech-biology-sexism][piece]] on “So why all the outrage?”.

[fn:3] I have to admit that I do not understand what ought to be claimed by “the underlying traits are highly heritable”, is that meant as a reference to IQ theory? Thus, I do not comment on that claim here.

[fn:4] I believe that “biological males that were castrated at birth and raised as females often still identify and act like males” is a reference to a case known as “John/Joan” in the research literature. Jordan-Young discusses this case in Chapter 1.

[fn:5] She writes: “I ultimately analyzed virtually every study on the ostensible prenatal hormone-sexuality connection published from 1967, when the theory was first applied to humans, up to the year 2000, when the increased flow of research in this area made it no longer possible to examine every published study in depth. I continued to examine all major studies (those published in the most important journals, those that garnered a lot of scientific attention, and those by well-established scientists) through 2008.”

[fn:6] From the memo: “Women generally also have a stronger interest in people rather than things, relative to men (also interpreted as empathizing vs. systemizing).”

[fn:7] The study tested 44 boys, 11 looked longer at the face, 19 longer at the mobile and 14 did not show a clear “preference”. The study tested 58 girls, 21 looked longer at the face, 10 looked longer at the mobile and 27 showed no clear “preference“.

[fn:8] Critics have pointed to (a) contradictions between different essays in the collection and (b) poor scholarship, e.g. that Hilary Rose attributed the quote “If Nature is sexist don’t blame her sons” to David Barash in /The Whispering Within/ who actually wrote (on a different page): “If male-female differences are sexist, we should put the blame where it really belongs, on the greatest sexist of all: ‘Mother’ Nature!“

[fn:9] Not all behavioural traits need to be adaptations, they also allow for side-effects of such adaptations.

[fn:10] From the memo: “We all have biases and use motivated reasoning to dismiss ideas that run counter to our internal values. Just as some on the Right deny science that runs counter to the ’God > humans > environment’ hierarchy (e.g., evolution and climate change) the Left tends to deny science concerning biological differences between people (e.g., IQ [8] and sex differences).“

[fn:11] I do not know how the memo’s author arrived at his conclusions, people can overlook contradictions etc. hence the word “seems”. I should also mention that approaching scientific results this way is not the privilege of the memo but rather common.

[fn:12] From the memo: “Note that contrary to what a social constructionist would argue, research suggests that ’greater nation-level gender equality leads to psychological dissimilarity in men’s and women’s personality traits.’ Because as ’society becomes more prosperous and more egalitarian, innate dispositional differences between men and women have more space to develop and the gap that exists between men and women in their personality becomes wider.’ We need to stop assuming that gender gaps imply sexism.”

[fn:13] The usual caveats about leading questions etc. apply.

