#+POSTID: 587
#+DATE: [2011-09-13 Tue 09:18]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: cryptography
#+TAGS: cryptanalysis, cryptography, it security
#+TITLE: This looks interesting: Code Audit Feed

#+BEGIN_QUOTE
You're a developer. And you've spent the last 2 years working with Java sockets in an uninteresting trading app. But you also happen to support anonymity - but have no idea how to get involved. Or you're a security researcher who's spent the last two months understanding the padding oracle backwards and forwards. Wouldn't it be nice to see a personalized RSS feed of cryptography, anonymity, and privacy projects containing the keywords "java.net.Socket" or "CBC Mode"? Then you could skim commits, and if something interesting came up, you may be able to lend your expertise. That's exactly what the Code Audit Feed is for.

The goal is to aggregate relevant open source projects, watch their commits, and deliver personalized information via RSS, email, and a web interface to encourage people to get involved with projects and audit and improve the code. Development and Design are in the early stages, with a [[https://github.com/cryptodotis/code-audit-feed][github repo located here]]. If interested, you can find the developer(s) on[[https://crypto.is/about/][the crypto.is IRC channel]].
#+END_QUOTE

Website: [[https://crypto.is/projects/audit/]] (via: [[https://blog.crypto.is/TCP-Newsletter-One/]])



